[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# didkit = { version = "0.4.0", features = ["wasm"] }
yew = "0.19"
